{{- if and (not .Values.secret.existingSecret) .Values.secret.data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "groundtruth.fullname" . }}
  labels:
    {{- include "groundtruth.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
